import * as pdfjsLib from 'pdfjs-dist'
import pdfWorkerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url'
import type { ParseResult } from './text'
import { parseMobSFText } from './text'

// pdfjs requires a worker. The ?url import asks Vite to copy and fingerprint
// the worker file, and to return a URL that resolves correctly under the
// GitHub Pages base path.
pdfjsLib.GlobalWorkerOptions.workerSrc = pdfWorkerUrl

/**
 * Extract text from a MobSF PDF report and parse it via the shared text
 * parser. The PDF is generated by MobSF from the same template as the
 * HTML view, so the section structure is consistent across versions.
 */
export async function parseMobSFPDF(file: File): Promise<ParseResult> {
  const buf = await file.arrayBuffer()
  let pdf
  try {
    pdf = await pdfjsLib.getDocument({ data: buf }).promise
  } catch (e) {
    throw new Error(
      `Could not open PDF: ${(e as Error).message}. ` +
        `Is the file actually a PDF, not a renamed JSON or HTML?`
    )
  }

  let combined = ''
  for (let i = 1; i <= pdf.numPages; i++) {
    const page = await pdf.getPage(i)
    const tc = await page.getTextContent()
    // pdfjs returns items with raw .str and an optional EOL marker. Reassemble
    // lines roughly by joining strings, inserting newlines on EOL markers.
    const parts: string[] = []
    let prevY: number | null = null
    for (const item of tc.items as Array<{ str: string; transform?: number[] }>) {
      const y = item.transform ? item.transform[5] : null
      if (prevY !== null && y !== null && Math.abs(prevY - y) > 2) {
        parts.push('\n')
      } else if (parts.length > 0) {
        parts.push(' ')
      }
      parts.push(item.str)
      prevY = y
    }
    combined += parts.join('') + '\n\n'
  }

  const result = parseMobSFText(combined)
  if (result.findings.length === 0) {
    throw new Error(
      'PDF parsed but no MobSF findings were detected. ' +
        'If you have the JSON export, that path is more reliable.'
    )
  }
  return result
}
