import type { MobSFFinding, AppMetadata, Severity } from '../../types'

export interface ParseResult {
  metadata: AppMetadata
  findings: MobSFFinding[]
}

/**
 * Parses MobSF report text — the flattened content shared between the
 * PDF and HTML exports. Both formats come from the same Jinja template,
 * so the section structure (APP INFORMATION, MANIFEST ANALYSIS, etc.)
 * and column ordering are identical; only the surrounding markup differs.
 *
 * This parser is best-effort and lossy compared to JSON. It will get the
 * triage-relevant data: titles, severities, descriptions, component names,
 * permissions, secrets. It cannot recover precise file paths, line numbers,
 * or CWE/MASVS tags that MobSF strips when rendering.
 */
export function parseMobSFText(text: string): ParseResult {
  // Normalize whitespace once. Keep newlines as separators but collapse
  // long runs of spaces that PDF extraction often introduces.
  const norm = text
    .replace(/\r\n?/g, '\n')
    .replace(/[ \t]+/g, ' ')
    .replace(/\n{3,}/g, '\n\n')

  const metadata = extractMetadata(norm)
  const findings: MobSFFinding[] = []

  findings.push(...extractPermissions(norm))
  findings.push(...extractManifest(norm))
  findings.push(...extractCertificate(norm))
  findings.push(...extractNetworkSecurity(norm))
  findings.push(...extractCodeAnalysis(norm))
  findings.push(...extractSecrets(norm))
  findings.push(...extractTrackers(norm))

  return { metadata, findings }
}

// ---- metadata ----

function extractMetadata(text: string): AppMetadata {
  const m = (re: RegExp) => text.match(re)?.[1]?.trim() ?? ''
  return {
    appName: m(/App Name:\s*([^\n]+)/i),
    packageName: m(/Package Name:\s*([^\s\n]+)/i),
    versionName:
      m(/Android Version Name:\s*([^\n]+)/i) ||
      m(/Version Name:\s*([^\n]+)/i),
    fileName: m(/File Name:\s*([^\n]+)/i),
    appType: 'android', // PDF/HTML report doesn't expose source language; defaulted
    mobsfVersion: m(/MobSF\s+v?([\d.]+)/i),
  }
}

// ---- section extraction helpers ----

/** Carves out the body of a section between its header and the next header. */
function section(text: string, header: RegExp, end: RegExp): string {
  const start = text.search(header)
  if (start === -1) return ''
  const after = text.slice(start)
  const endIdx = after.slice(20).search(end) // skip the header itself
  if (endIdx === -1) return after
  return after.slice(0, endIdx + 20)
}

// All section headers MobSF uses, used as terminators for each other
const SECTION_END =
  /(APPLICATION PERMISSIONS|APKID ANALYSIS|NETWORK SECURITY|CERTIFICATE ANALYSIS|MANIFEST ANALYSIS|CODE ANALYSIS|NIAP ANALYSIS|ABUSED PERMISSIONS|TRACKERS|HARDCODED SECRETS|POSSIBLE SECRETS|SCAN LOGS|FILE INFORMATION|APP INFORMATION|APP COMPONENTS|CERTIFICATE INFORMATION|Report Generated by)/i

// ---- permissions ----

function extractPermissions(text: string): MobSFFinding[] {
  const body = section(text, /APPLICATION PERMISSIONS/i, SECTION_END)
  if (!body) return []
  const out: MobSFFinding[] = []

  // Lines look like:
  //   android.permission.READ_SMS dangerous read SMS messages Allows ...
  // Permission name → status → info → description (Allows ...)
  const re =
    /(android\.permission\.[A-Z_]+)\s+(normal|dangerous|signature|signatureOrSystem|unknown)\s+([^]+?)(?=\s*android\.permission\.|\s*APKID ANALYSIS|\s*NETWORK SECURITY|\s*MANIFEST ANALYSIS|$)/gi

  let m: RegExpExecArray | null
  while ((m = re.exec(body)) !== null) {
    const [, perm, status, rest] = m
    if (status.toLowerCase() !== 'dangerous' && status.toLowerCase() !== 'signature') continue

    // rest = "<info text> Allows <description>"
    const allowsIdx = rest.search(/\bAllows\b/i)
    const info = allowsIdx === -1 ? rest.trim() : rest.slice(0, allowsIdx).trim()
    const description =
      allowsIdx === -1 ? '' : rest.slice(allowsIdx).trim().replace(/\s+/g, ' ')

    out.push({
      id: `perm:${perm}`,
      category: 'permissions',
      ruleId: perm,
      title: perm,
      description: description.slice(0, 600),
      severity: status.toLowerCase() === 'dangerous' ? 'warning' : 'info',
      evidence: `Status: ${status.toLowerCase()} · ${info}`.slice(0, 400),
    })
  }
  return out
}

// ---- manifest ----

function extractManifest(text: string): MobSFFinding[] {
  const body = section(text, /MANIFEST ANALYSIS/i, SECTION_END)
  if (!body) return []
  return parseNumberedFindings(body, 'manifest')
}

// ---- code analysis ----

function extractCodeAnalysis(text: string): MobSFFinding[] {
  const body = section(text, /CODE ANALYSIS/i, SECTION_END)
  if (!body) return []
  return parseNumberedFindings(body, 'code_analysis')
}

// ---- network security ----

function extractNetworkSecurity(text: string): MobSFFinding[] {
  const body = section(text, /NETWORK SECURITY/i, SECTION_END)
  if (!body) return []
  return parseNumberedFindings(body, 'network_security')
}

/**
 * Generic parser for MobSF's numbered-table sections (manifest, code
 * analysis, network security). Each finding row in the PDF/HTML is:
 *
 *   <N> <issue title spanning 1-N lines> <severity> <description...>
 *
 * The next row starts when a new line begins with another digit.
 */
function parseNumberedFindings(
  body: string,
  category: MobSFFinding['category']
): MobSFFinding[] {
  // Drop the header line itself so we don't accidentally parse "NO ISSUE..."
  const stripped = body
    .replace(/.*?(NO\s+ISSUE\s+SEVERITY\s+DESCRIPTION|HIGH:\s*\d+)[^\n]*/i, '')
  const lines = stripped.split('\n').map((l) => l.trim()).filter(Boolean)

  type Group = { num: number; raw: string }
  const groups: Group[] = []
  let current: Group | null = null

  for (const line of lines) {
    // Line starts a new finding if it begins with a number followed by
    // either whitespace or end-of-line. Avoid matching things like "1.0"
    // or "API 29".
    const leading = line.match(/^(\d{1,3})(?:\s+|$)/)
    if (leading && parseInt(leading[1], 10) <= 200) {
      if (current) groups.push(current)
      current = { num: parseInt(leading[1], 10), raw: line.replace(/^\d{1,3}\s*/, '') }
    } else if (current) {
      current.raw += ' ' + line
    }
  }
  if (current) groups.push(current)

  const out: MobSFFinding[] = []
  for (const g of groups) {
    const parsed = splitTitleSeverityDescription(g.raw)
    if (!parsed) continue
    out.push({
      id: `${category}:${g.num}`,
      category,
      ruleId: extractRuleId(parsed.title) || `${category}_${g.num}`,
      title: parsed.title.slice(0, 240),
      description: parsed.description.slice(0, 1200),
      severity: parsed.severity,
      evidence: extractEvidence(parsed.title, parsed.description),
    })
  }
  return out
}

function splitTitleSeverityDescription(
  raw: string
): { title: string; severity: Severity; description: string } | null {
  // Severity word appears between title and description.
  const m = raw.match(/^(.+?)\s+(high|warning|medium|low|info)\s+(.+)$/i)
  if (!m) return null
  const sev = normalizeSeverity(m[2])
  if (!sev) return null
  return {
    title: m[1].trim().replace(/\s+/g, ' '),
    severity: sev,
    description: m[3].trim().replace(/\s+/g, ' '),
  }
}

function extractRuleId(title: string): string {
  // MobSF often embeds the manifest attribute in brackets, e.g.
  //   "[android:debuggable=true]" or "[android:exported=true]"
  const bracket = title.match(/\[([^\]]+)\]/)
  if (bracket) return bracket[1].split('=')[0].trim()
  // Or the Activity/Service name in parens
  const paren = title.match(/\(([^)]+)\)/)
  if (paren) return paren[1].trim()
  // Fallback: first few words slugified
  return title.toLowerCase().replace(/[^a-z0-9]+/g, '_').slice(0, 60)
}

function extractEvidence(title: string, _description: string): string {
  // Pull out the component/attribute names from the title (parens/brackets).
  const bits: string[] = []
  const paren = title.match(/\(([^)]+)\)/)
  if (paren) bits.push(paren[1])
  const bracket = title.match(/\[([^\]]+)\]/)
  if (bracket) bits.push(bracket[1])
  return bits.join(' · ')
}

// ---- certificate analysis ----

function extractCertificate(text: string): MobSFFinding[] {
  const body = section(text, /CERTIFICATE ANALYSIS/i, SECTION_END)
  if (!body) return []
  const out: MobSFFinding[] = []

  // Cert section is a table with rows: <title> <severity> <description>
  // Drop the column header line first.
  const stripped = body.replace(/.*?TITLE\s+SEVERITY\s+DESCRIPTION[^\n]*/i, '')
  const lines = stripped
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l && !/^HIGH:|^WARNING:|^INFO:/.test(l))

  // Join wrapped lines into rows: a row ends when we see a severity word
  // followed by a description. Use a forward scan.
  let buffer = ''
  let rowIdx = 0
  for (const line of lines) {
    buffer = buffer ? buffer + ' ' + line : line
    const m = buffer.match(/^(.+?)\s+(high|warning|info)\s+(.+)$/i)
    if (m && m[3].length > 10) {
      const sev = normalizeSeverity(m[2])
      if (sev) {
        out.push({
          id: `cert:${rowIdx++}`,
          category: 'certificate',
          ruleId: `cert_${rowIdx}`,
          title: m[1].trim().slice(0, 240),
          description: m[3].trim().slice(0, 1000),
          severity: sev,
          evidence: '',
        })
      }
      buffer = ''
    }
  }
  return out
}

// ---- secrets ----

function extractSecrets(text: string): MobSFFinding[] {
  const body = section(
    text,
    /(HARDCODED SECRETS|POSSIBLE SECRETS)/i,
    /(SCAN LOGS|Report Generated by|TRACKERS|ABUSED PERMISSIONS|$)/i
  )
  if (!body) return []
  const stripped = body.replace(/.*?(HARDCODED SECRETS|POSSIBLE SECRETS)/i, '')
  const lines = stripped
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean)
    .filter((l) => l !== 'POSSIBLE SECRETS')

  const out: MobSFFinding[] = []
  lines.forEach((value, idx) => {
    // Skip very short or obviously non-secret lines
    if (value.length < 8 || value.length > 800) return
    out.push({
      id: `secret:${idx}`,
      category: 'secrets',
      ruleId: 'hardcoded_secret',
      title: 'Possible hardcoded secret',
      description: 'A string matched a known secret/key pattern.',
      severity: 'warning',
      evidence: value.slice(0, 400),
    })
  })
  return out
}

// ---- trackers ----

function extractTrackers(text: string): MobSFFinding[] {
  const body = section(text, /^\s*TRACKERS\s*$/im, SECTION_END)
  if (!body) return []
  const out: MobSFFinding[] = []

  // Tracker rows: <name> <category> https://...
  const re = /([A-Z][\w &.-]+?)\s+(Advertisement|Analytics|Crash reporting|Profiling|Identification|Location)\s+(https?:\/\/\S+)/gi
  let m: RegExpExecArray | null
  let idx = 0
  while ((m = re.exec(body)) !== null) {
    out.push({
      id: `tracker:${idx++}`,
      category: 'trackers',
      ruleId: m[1].trim(),
      title: `Tracker detected: ${m[1].trim()}`,
      description: m[2].trim(),
      severity: 'info',
      evidence: m[3].trim(),
    })
  }
  return out
}

// ---- shared ----

function normalizeSeverity(s: unknown): Severity | null {
  if (typeof s !== 'string') return null
  const lc = s.toLowerCase().trim()
  if (lc === 'high' || lc === 'critical') return 'high'
  if (lc === 'warning' || lc === 'medium' || lc === 'low') return 'warning'
  if (lc === 'info' || lc === 'informational') return 'info'
  return null
}
